### ISSUE TITLE
App does only sync the root folder of the dropbox

### ISSUE THREAD

**Issue by devjb** [icewind1991/files_external_dropbox#13]
After I got the Oauth working from #3, I still suffer from #11, which might be related with something new I just noticed. 

The app syncs the dropbox root folder successfully and also displays the sub folders. But the content of neither sub folder is synced at all.

**Comment by hermanntoast** [comment]
Heres the same problem. I see the root folder, but not the folders behind it.

**Comment by icewind1991** [comment]
Should be fixed with https://github.com/icewind1991/files_external_dropbox/commit/c587c3e9f299a247e53f92da54bffbd22ac86816 so please retry with latest master.

Note that you probably need to run `occ files:scan` to repair invalid cached data.

**Comment by voodoomatz** [comment]
Nope, latest master did not solve the issue for me.
