### ISSUE TITLE
invalid_client: The OAuth client was not found

### ISSUE THREAD

**Issue by jfsalzmann** [icewind1991/files_external_dropbox#14]
Hi guys, I get an error when I add the external storage on the admin page. Yet the indicator turns green
![unbenannt](https://user-images.githubusercontent.com/11268548/32705028-a4702be0-c80f-11e7-9df1-50870bc5e49e.JPG)

> Schritt 2 fehlgeschlagen. Fehlermeldung: Error fetching OAuth2 access token, message: 'invalid_client: The OAuth client was not found

Any idea what's wrong? I'm not that much into all the nextcloud stuff, just tried to follow the installation tutorial.

**Comment by ConorIA** [comment]
I'm experiencing the same over on #3.

**Comment by jc97** [comment]
Same here. Does some know the reason for that?

**Comment by ShortnStubby** [comment]
Wanted to chime in here as well, when I go to add Client ID and Secret, Click grand access, the first time it takes me to dropbox page, I accept/authorize and then it pops up 

Error configuring OAuth2

Step 2 failed. Exception: Error fetching OAuth2 access token, message: 'invalid_client: The OAuth client was not found.'

The fields turn green but nothing shows up in folder, if i check nextcloud log it is filled with:

![image](https://user-images.githubusercontent.com/30622357/33372133-e7d08e3a-d4ca-11e7-82c3-6601300d3392.png)

Thank you.

**Comment by Thx3r** [comment]
Same Here. Any news ? :)

**Comment by SpontEIN** [comment]
Similar here.

dropbox external storage was added as admin.

The dropboxv2 entry turns green and the folder and subfolders show up. However the content of all folders in the dropbox is empty (although they are in fact not).

**Comment by MiGo2000** [comment]
For me exactly the same on nextcloud 12.0.4

Message: Error fetching OAuth2 access token, message: 'invalid_client: The OAuth client was not found.'

Button turns green, I can see the folders, but they are empty.
I am able to create and delete folders in my dropbox from nextcloud, but not the other way round: Creating a folder in dropbox would not be seen in nextcloud.

So something is working, but not in both directions.

**Comment by icewind1991** [comment]
The "empty folder" issues is reported in https://github.com/icewind1991/files_external_dropbox/issues/13 and should be fixed with latest master (run `occ files:scan` after upgrading).

The error message from the original issue seems to be harmless and caused during the setup OAuth juggling from what I can tell.
