### ISSUE TITLE
Dropbox path is shared across all users

### ISSUE THREAD

**Issue by notjoe** [icewind1991/files_external_dropbox#7]
The dropbox share added isn't user specific. All users of my Nextcloud installation are able to see all the files stored within the dropbox share.

To reproduce:
Under Account A upload some content into the Dropbox folder.
Under Account B go into the dropbox folder and download Account A's file. 

I'd imagine that each user should have their own directory under the share ?

**Comment by ConorIA** [comment]
This is probably a silly question, but are you adding the file under the "Admin" menu or under the "Personal" menu?

**Comment by notjoe** [comment]
Under Admin. Ideally I'd list to have all users have their own private storage inside of the Dropbox share and use that for the primary storage sort of like what you can do with S3

**Comment by icewind1991** [comment]
This is expected behavior for external storages, if you need seperate storages per user then you have to configure it like that.
